# Generated by Django 5.2.6 on 2025-09-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywolbrand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='object_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mywolbrand.property'),
        ),
        migrations.AddField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
