# Generated by Django 5.2.6 on 2025-09-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywolbrand', '0002_remove_bid_content_type_remove_bid_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mywolbrand.sellitem'),
        ),
    ]
