# Generated by Django 5.2.6 on 2025-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywolbrand', '0003_alter_bid_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellitem',
            name='contact_requested',
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='house_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('mansion', 'Mansion'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='location',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
