# Generated by Django 5.2.6 on 2025-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywolbrand', '0006_loginactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginactivity',
            old_name='timestamp',
            new_name='login_time',
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='login_success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='user_agent',
            field=models.TextField(),
        ),
    ]
