# Generated by Django 5.2.6 on 2025-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywolbrand', '0008_alter_loginactivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='attempted_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
