# Generated by Django 5.2.6 on 2025-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywolbrand', '0009_loginactivity_attempted_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
