# Generated by Django 5.2.6 on 2025-09-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywolbrand', '0010_property_is_sold_sellitem_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_sold',
            field=models.BooleanField(),
        ),
    ]
